### ISSUE TITLE
This repository doesn't have a license

### ISSUE THREAD

**Issue by Moini** [Aly-ve/Mastodon-share-button#10]
Hi, @Aly-ve !

This is some nice piece of code that I might like to use on a website I'm building.

Can you please clarify what its license is?

Thank you!

**Comment by Aly-ve** [comment]
Hello @Moini 
I'm sorry I forget to put a license.
You can do what you want with this code but do not sell it, that's it.
And I we meet us one day, a cup of tea will be enough. 👌

**Comment by Moini** [comment]
Great, thanks! It's going to be a non-commercial website for a linux event in Germany (I'm rewriting https://kielux.de), so that should work :)

I'm probably going to shorten your script quite a bit, because I've got my own little CSS framework, complete with modals and all, and I need it to work on a link, not a button. The cookie and the mastodon parts are what will be really useful!

I like tea, too - if I ever visit FOSDEM, we can meet for :tea:

**Comment by rugk** [comment]
> You can do what you want with this code but do not sell it, that's it.

Just writing this in an issue on GitHub is not enough and it is also not a legally valid license.

So could you please [add your license to your repo](https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository)? It is a common standard that licenses should be placed into a file called `LICENSE.md`, `LICENSE` or `LICENSE.txt`.
You can find [good licenses here, e.g.](https://choosealicense.com/)

In your case maybe the dwtfywtd license or just CC0 or so could be what you want in case you really want to allow everything.

**Comment by Aly-ve** [comment]
Done, thank you. ^^
Usually, I don't care about license, I just do it for fun. Please enjoy.

**Comment by Moini** [comment]
Thank you!
