### ISSUE TITLE
Is this the "canonical" way to add mastodon share buttons

### ISSUE THREAD

**Issue by cs224** [Aly-ve/Mastodon-share-button#11]
Sorry for that stupid question, but I am new to mastodon. I'd like to add a sharing button to my web-site similar to https://sharingbuttons.io/, ideally in the small version without text.

I've read somewhere that this functionality: https://github.com/tootsuite/mastodon/pull/8202
Should allow to add a sharing button. But I am not sure how?

So: what is the canconical way to add a sharing button to your web-site?

And ideally: how can I do this in a "small" format. Currently the Mastodon-share-button seems to always require the text part to click on it.

**Comment by rugk** [comment]
Yes tootsuite/mastodon#8202 does basically the same as this project hee does. The idea is the same: Enter your Mastodon handle and then get redirected. :smile:

**Comment by rugk** [comment]
And thanks for hinting me to that other project. I've created and issue for them: https://github.com/mxstbr/sharingbuttons.io/issues/99 :wink:
