### ISSUE TITLE
Auto-focus on popup open

### ISSUE THREAD

**Issue by rugk** [Aly-ve/Mastodon-share-button#12]
If the popup is opened the Mastodon handle input should be auto-focused, so the user can start to type immediately.

On your test site https://aly-ve.github.io/Mastodon-share-button/, this does not work.

Firefox 71

**Comment by Aly-ve** [comment]
Hello @rugk 

In this case, it's a about bootstrap but I agree, I fucked up this point.
On your own Javascript, you must add:

``` javascirpt
openModal: function () {
    $('#exampleModal').modal('show');
    $('#exampleModal').on('shown.bs.modal', function() {
        $('#msb-address').focus();
    }); 
},
```

And it work fine.
Otherwise, you can use the `autofocus` from HTML5.

I hope it will help you.

Alyve

**Comment by rugk** [comment]
Yeah, just was about the demo site. (Respectively I thought this was included in here.)

Anyway, verified as fixed on the demo site, thus closing.
