### ISSUE TITLE
Can I parse this in a browser extension?

### ISSUE THREAD

**Issue by rugk** [Aly-ve/Mastodon-share-button#13]
I am a browser extension/add-on dev and I do have developed [an add-on](https://github.com/rugk/mastodon-simplified-federation).
It basically skips the step "enter your mastodon" handle for Mastodons own/"internal" pages.

There already was some discussion about how one could do the same with a sharing button or so.

@wiktor-k and @SoniEx2 (and me uhm) did already discuss this in https://github.com/rugk/mastodon-simplified-federation/issues/31 e.g. and we came to a conclusion that we need to have some kind of "standardized" sharing button implemented by many websites to make this work.

Now, this project could at least become a de-factor standard if many websites use it.
So what do you think about the idea if I'd parse your HTML (the data attributes will likely be the most convenient method) and intercept clicks on it, so it does instantly redirect to a share page? :smile: 
(if the user uses the add-on)

If I could intercept an URL (request), that would be even easier to integrate, but that is likely not possible(?).
Notice I do plan to support/redirect the web.mastodon:// protocol optionally, see https://github.com/rugk/mastodon-simplified-federation/issues/32

**Comment by rugk** [comment]
If we should do so, we could of course also "advertise" these projects mutually. (as my thing would have a setting likely, I could obviously include a link there)

**Comment by Aly-ve** [comment]
Hello,
Of course you can. I don't have any problem by using MSB's code.

**Comment by rugk** [comment]
What do you think about linking it on the demo site/Readme once this is integrated?

----

Okay then I've opened https://github.com/rugk/mastodon-simplified-federation/issues/52 on my site about this feature.
As for your project I guess the only point to be useful to have would be to somehow keep the "API" stable, i.e. the `data`  attributes may not be changed – at it's best. :smiley:
