### ISSUE TITLE
Weird wording in index.html

### ISSUE THREAD

**Issue by Joshix-1** [Aly-ve/Mastodon-share-button#19]
> Easy to use
> It works without any library

Then why do you use bootstrap and jQuery to make the button work?

How could I easily use it without library?

**Comment by Aly-ve** [comment]
Good morning.

I hope you had a wonderful day. Thank you for your lack of courtesy.

As I wrote on the README.md 3 years ago:

![Screenshot 2022-04-29 at 22-51-14 Aly-ve_Mastodon-share-button Add autotically a button to share content with your Mastodon account](https://user-images.githubusercontent.com/8679006/166067556-6b05fdac-5627-42ad-a61a-36ce79af20cf.png)
![Screenshot 2022-04-29 at 22-51-06 Aly-ve_Mastodon-share-button Add autotically a button to share content with your Mastodon account](https://user-images.githubusercontent.com/8679006/166067558-b20946f5-41f4-4554-8923-2d432430205a.png)

The only jquery you will find exists to select the html id and open the modal. The entire script is agnostic of what you are using.

Don't forget one thing: humans are behing displays. Be kind.

```html
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Mastodon Share Button</title>
</head>

<body>
  <div
    class="mastodon-share-button"
     data-target="https://aly-ve.github.io/Mastodon-share-button/"
     data-name="Test of #MSB"
     data-buttonstyle="anything-you-want"
     data-text="Share on Mastodon"
  ></div>

  <div id="modal" style="display: none;">
    <label for="msb-address" name="instanceAddress">Instance address</label>
    <input id="msb-address" type="text" />
    <label for="msb-memorize-instance">Memorize instance</label>
    <input type="checkbox" id="msb-memorize-instance" />
    <button id="msb-share">share</button>
  </div>

  <script>
    const msbConfig = {
      openModal: function () {
        document.getElementById('modal').style.display = 'block';
      },
      closeModal: function () {
        document.getElementById('modal').style.display = 'none';
      },
      addressFieldSelector: '#msb-address',
      buttonModalSelector: '#msb-share',
      memorizeFieldId: 'msb-memorize-instance',
      buttonIconHtml: '<i class="fa fa-mastodon" aria-hidden="true"></i>'
    };
  </script>

  <script src="https://aly-ve.github.io/Mastodon-share-button/dist/mastodon.js"></script>
</body>
</html>
```
