### ISSUE TITLE
[Done] Feature: I18N for button text 

### ISSUE THREAD

**Issue by ghost** [Aly-ve/Mastodon-share-button#2]
Great work!

I suggest to to make the button text I18N capable. The line https://github.com/Aly-ve/Mastodon-share-button/blob/4a6851244b77f6a9a5b3661d2c896a4758319b02/dist/mastodon.js#L70 now uses the fixed text `Toot`. This should be configurable, for example Mastodon uses `Tröt` for German.

**Comment by Aly-ve** [comment]
Hello @lutzhorn 
This feature will be implemented soon as possible. Thank you for your return. 👍

**Comment by Aly-ve** [comment]
Done. :)
