### ISSUE TITLE
Add `https://` if missing

### ISSUE THREAD

**Issue by IanVS** [Aly-ve/Mastodon-share-button#20]
I tried entering `fosstodon.org`, and got an error page:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/4616705/208958652-e202e1a3-d568-4f19-b17b-7497be7f1016.png">

Maybe you could detect that it's missing, and add it automatically if needed?

**Comment by Aly-ve** [comment]
Hello,
Thank you for your issue. I am sorry I didn't see the mail sooner. @mediaformat did it, thanks to him/her.
